[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "secagent"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "docstring_parser",
    "jsonschema",
    "pydantic>2.0",
    "openai",
    "anthropic",
]
